# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-01-20 07:21
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('fileupload', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequestedFiles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fileupload.Files')),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='users',
            name='role',
            field=models.CharField(choices=[('1', 'Patient'), ('2', 'Doctor'), ('3', 'Pharmacist')], default='1', max_length=1),
        ),
    ]
