# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-01-20 07:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fileupload', '0003_auto_20180120_0732'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestedfiles',
            name='requested_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='requested_by', to='fileupload.Users'),
        ),
    ]
