# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-01-20 13:51
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('fileupload', '0005_auto_20180120_0745'),
    ]

    operations = [
        migrations.AddField(
            model_name='files',
            name='created',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2018, 1, 20, 13, 51, 6, 525294, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='requestedfiles',
            name='requested_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='requested_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
