# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-01-20 13:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fileupload', '0006_auto_20180120_1351'),
    ]

    operations = [
        migrations.RenameField(
            model_name='files',
            old_name='created',
            new_name='file_created',
        ),
    ]
