# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-01-21 13:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fileupload', '0007_auto_20180120_1354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='files',
            name='file_created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
